export const SIGNUP_ADMIN = 'SIGNUP_ADMIN';
export const LOGIN_ADMIN = 'LOGIN_ADMIN';
export const SET_CURRENT_ADMIN = 'SET_CURRENT_ADMIN';
export const LOGOUT_ADMIN = 'LOGOUT_ADMIN';
export const SHOWADMIN_PROFILE = 'SHOWADMIN_PROFILE';
export const UPDATEADMIN_PROFILE = 'UPDATEADMIN_PROFILE';

export const UPLOAD_EXAM = 'UPLOAD_EXAM';
export const UPLOAD_EXAMDETAILS = 'UPLOAD_EXAMDETAILS';
export const UPLOAD_SECDETAILS = 'UPLOAD_SECDETAILS';
export const GET_SEC = 'GET_SEC';
export const DELETE_EXAM = 'DELETE_EXAM';
export const DELETE_SEC = 'DELETE_SEC';
export const DELETE_QUE = 'DELETE_QUE';
export const UPLOAD_QUESTION = 'UPLOAD_QUESTION';
export const STUDENT_LIST = 'STUDENT_LIST';
export const GET_EXAMS = 'GET_EXAMS';

export const HOST_EXAM = 'HOST_EXAM';

export const HOSTED_EXAM = 'HOSTED_EXAM';
export const RANK_LIST = 'RANK_LIST';
